export const LOAD_CONFIG = "LOAD_CONFIG";
export const LOAD_GRAPHS = "LOAD_GRAPHS";

export const SET_CONFIG_LOADED = "SET_CONFIG_LOADED";
export const SET_CURRENT_TAB = "SET_CURRENT_TAB";

export const SET_SHOW_INDICATE_CONFIG = "SET_SHOW_INDICATE_CONFIG";
export const SET_SHOW_CONFIG_IS_LOADING = "SET_SHOW_CONFIG_IS_LOADING";
export const SET_SHOW_VPN_ENABLED = "SET_SHOW_VPN_ENABLED";
export const SET_SHOW_VPN_DISABLED = "SET_SHOW_VPN_DISABLED";
export const SET_SHOW_CONFIG_LOADED = "SET_SHOW_CONFIG_LOADED";
export const SET_SHOW_CONFIG_LOADED_ERROR = "SET_SHOW_CONFIG_LOADED_ERROR";
export const TOGGLE_DATES = "TOGGLE_DATES";
